### ISSUE TITLE
Content translation and required Drupal core patch

### ISSUE THREAD

**Issue by vever001** [openeuropa/oe_paragraphs#43] opened 2019-04-10 14:23 UTC
Hello,

After installing oe_paragraphs, I had the following SQL error on content creation:
```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Core\Entity\EntityStorageException</em>: SQLSTATE[42S22]: Column not found: 1054 Unknown column &#039;content_translation_source&#039; in &#039;field list&#039;: INSERT INTO {paragraphs_item_field_data} (id, revision_id, type, langcode, status, created, parent_id, parent_type, parent_field_name, behavior_settings, default_langcode, revision_translation_affected, oe_paragraphs_variant, content_translation_source, content_translation_outdated, content_translation_changed) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14, :db_insert_placeholder_15); Array
(
    [:db_insert_placeholder_0] =&gt; 1
    [:db_insert_placeholder_1] =&gt; 1
    [:db_insert_placeholder_2] =&gt; oe_rich_text
    [:db_insert_placeholder_3] =&gt; en
    [:db_insert_placeholder_4] =&gt; 1
    [:db_insert_placeholder_5] =&gt; 1554905028
    [:db_insert_placeholder_6] =&gt; 
    [:db_insert_placeholder_7] =&gt; paragraph
    [:db_insert_placeholder_8] =&gt; field_oe_paragraphs
    [:db_insert_placeholder_9] =&gt; a:0:{}
    [:db_insert_placeholder_10] =&gt; 1
    [:db_insert_placeholder_11] =&gt; 1
    [:db_insert_placeholder_12] =&gt; default
    [:db_insert_placeholder_13] =&gt; und
    [:db_insert_placeholder_14] =&gt; 0
    [:db_insert_placeholder_15] =&gt; 1554905028
)
 in <em class="placeholder">Drupal\Core\Entity\Sql\SqlContentEntityStorage-&gt;save()</em> (line <em class="placeholder">783</em> of <em class="placeholder">core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php</em>).
```

Two questions:
1. Why is content_translation required for oe_paragraphs in the first place?
The website I'm working on is not multilingual.
Would it be possible to remove this hard dependency?

2. The patch for this error is https://www.drupal.org/node/2599228
It is applied on openeuropa/drupal-core-require-dev, which is why I couldn't reproduce it in my openeuropa test environment which took me a while to realize.
Please could we add a remark in the readme that this patch is required prior to Drupal core 8.8.x ?

**Comment by upchuk** [comment] 2019-04-22 07:12
@vever001 Sorry for the late reply. Created a Jira ticket and we will look into this.

**Comment by nagyad** [comment] 2019-05-07 09:45
@vever001 
The problem is not with the component but the content_translation. 
The patch note is included in our drupal site-template. However, since the patch you mentioned was merged on drupal 8.7 and we upgraded the component to 8.7 you can just reinstall. 

The component foresees translations in general. If your site is single uses one language, you can still use it by enabling that single language.

**Comment by vever001** [comment] 2019-05-07 10:53
Hi @nagyad 

Yes, I was mainly asking to document that patch somewhere for D8 <= 8.7.
I didn't spot the info in the drupal-site-template.

Besides oe_multilingual (of course), I believe oe_paragraphs is the only OE module that requires multilingual-related modules.
I was wondering if that could be avoided, mainly for websites that will, for sure, never be multilingual.
If that makes the OE component too complicated to maintain, I'd understand, but it's worth looking into it IMO.
If this is a definitive no then feel free to close this issue.

Thanks,
Hervé

**Comment by nagyad** [comment] 2019-05-07 12:55
We have removed this hard dependency from the component. Thank you for opening the issue.
https://github.com/openeuropa/oe_paragraphs/pull/50

**Closed by nagyad** 2019-05-07 12:55 UTC
